# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBD-MVS_FTPSQL
version:      0.38.14
version_from: lib/DBD/MVS_FTPSQL.pm
installdirs:  site
requires:
    Carp:                          0
    DBI:                           0
    IO::File:                      0
    Net::FTP:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
